// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.countAccountTransactionsStmt, err = db.PrepareContext(ctx, countAccountTransactions); err != nil {
		return nil, fmt.Errorf("error preparing query CountAccountTransactions: %w", err)
	}
	if q.createAccountStmt, err = db.PrepareContext(ctx, createAccount); err != nil {
		return nil, fmt.Errorf("error preparing query CreateAccount: %w", err)
	}
	if q.deleteAccountStmt, err = db.PrepareContext(ctx, deleteAccount); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAccount: %w", err)
	}
	if q.getAccountByIDStmt, err = db.PrepareContext(ctx, getAccountByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetAccountByID: %w", err)
	}
	if q.getAccountsSummaryStmt, err = db.PrepareContext(ctx, getAccountsSummary); err != nil {
		return nil, fmt.Errorf("error preparing query GetAccountsSummary: %w", err)
	}
	if q.listAccountsStmt, err = db.PrepareContext(ctx, listAccounts); err != nil {
		return nil, fmt.Errorf("error preparing query ListAccounts: %w", err)
	}
	if q.setAccountArchivedStmt, err = db.PrepareContext(ctx, setAccountArchived); err != nil {
		return nil, fmt.Errorf("error preparing query SetAccountArchived: %w", err)
	}
	if q.updateAccountStmt, err = db.PrepareContext(ctx, updateAccount); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateAccount: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.countAccountTransactionsStmt != nil {
		if cerr := q.countAccountTransactionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countAccountTransactionsStmt: %w", cerr)
		}
	}
	if q.createAccountStmt != nil {
		if cerr := q.createAccountStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createAccountStmt: %w", cerr)
		}
	}
	if q.deleteAccountStmt != nil {
		if cerr := q.deleteAccountStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAccountStmt: %w", cerr)
		}
	}
	if q.getAccountByIDStmt != nil {
		if cerr := q.getAccountByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAccountByIDStmt: %w", cerr)
		}
	}
	if q.getAccountsSummaryStmt != nil {
		if cerr := q.getAccountsSummaryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAccountsSummaryStmt: %w", cerr)
		}
	}
	if q.listAccountsStmt != nil {
		if cerr := q.listAccountsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAccountsStmt: %w", cerr)
		}
	}
	if q.setAccountArchivedStmt != nil {
		if cerr := q.setAccountArchivedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing setAccountArchivedStmt: %w", cerr)
		}
	}
	if q.updateAccountStmt != nil {
		if cerr := q.updateAccountStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateAccountStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                           DBTX
	tx                           *sql.Tx
	countAccountTransactionsStmt *sql.Stmt
	createAccountStmt            *sql.Stmt
	deleteAccountStmt            *sql.Stmt
	getAccountByIDStmt           *sql.Stmt
	getAccountsSummaryStmt       *sql.Stmt
	listAccountsStmt             *sql.Stmt
	setAccountArchivedStmt       *sql.Stmt
	updateAccountStmt            *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                           tx,
		tx:                           tx,
		countAccountTransactionsStmt: q.countAccountTransactionsStmt,
		createAccountStmt:            q.createAccountStmt,
		deleteAccountStmt:            q.deleteAccountStmt,
		getAccountByIDStmt:           q.getAccountByIDStmt,
		getAccountsSummaryStmt:       q.getAccountsSummaryStmt,
		listAccountsStmt:             q.listAccountsStmt,
		setAccountArchivedStmt:       q.setAccountArchivedStmt,
		updateAccountStmt:            q.updateAccountStmt,
	}
}
