// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package repository

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const countAccountTransactions = `-- name: CountAccountTransactions :one
SELECT COUNT(*)
FROM transactions
WHERE user_id = $1 AND (account_id = $2 OR to_account_id = $2)
`

type CountAccountTransactionsParams struct {
	UserID    uuid.UUID `json:"userId"`
	AccountID uuid.UUID `json:"accountId"`
}

func (q *Queries) CountAccountTransactions(ctx context.Context, arg CountAccountTransactionsParams) (int64, error) {
	row := q.queryRow(ctx, q.countAccountTransactionsStmt, countAccountTransactions, arg.UserID, arg.AccountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (user_id, name, type, balance, currency)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, name, type, balance, currency, is_archived, created_at, updated_at
`

type CreateAccountParams struct {
	UserID   uuid.UUID   `json:"userId"`
	Name     string      `json:"name"`
	Type     AccountType `json:"type"`
	Balance  string      `json:"balance"`
	Currency string      `json:"currency"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.queryRow(ctx, q.createAccountStmt, createAccount,
		arg.UserID,
		arg.Name,
		arg.Type,
		arg.Balance,
		arg.Currency,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Balance,
		&i.Currency,
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :execrows
DELETE FROM accounts
WHERE id = $1 AND user_id = $2
`

type DeleteAccountParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"userId"`
}

func (q *Queries) DeleteAccount(ctx context.Context, arg DeleteAccountParams) (int64, error) {
	result, err := q.exec(ctx, q.deleteAccountStmt, deleteAccount, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, user_id, name, type, balance, currency, is_archived, created_at, updated_at
FROM accounts
WHERE id = $1 AND user_id = $2
LIMIT 1
`

type GetAccountByIDParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"userId"`
}

func (q *Queries) GetAccountByID(ctx context.Context, arg GetAccountByIDParams) (Account, error) {
	row := q.queryRow(ctx, q.getAccountByIDStmt, getAccountByID, arg.ID, arg.UserID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Balance,
		&i.Currency,
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountsSummary = `-- name: GetAccountsSummary :one
SELECT
    COALESCE(SUM(balance), 0)::text AS total_balance,
    COUNT(*) AS total_accounts
FROM accounts
WHERE user_id = $1 AND is_archived = FALSE
`

type GetAccountsSummaryRow struct {
	TotalBalance  string `json:"totalBalance"`
	TotalAccounts int64  `json:"totalAccounts"`
}

func (q *Queries) GetAccountsSummary(ctx context.Context, userID uuid.UUID) (GetAccountsSummaryRow, error) {
	row := q.queryRow(ctx, q.getAccountsSummaryStmt, getAccountsSummary, userID)
	var i GetAccountsSummaryRow
	err := row.Scan(&i.TotalBalance, &i.TotalAccounts)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, user_id, name, type, balance, currency, is_archived, created_at, updated_at
FROM accounts
WHERE user_id = $1
  AND ($2::boolean IS TRUE OR is_archived = FALSE)
ORDER BY is_archived, name
`

type ListAccountsParams struct {
	UserID          uuid.UUID    `json:"userId"`
	IncludeArchived sql.NullBool `json:"includeArchived"`
}

func (q *Queries) ListAccounts(ctx context.Context, arg ListAccountsParams) ([]Account, error) {
	rows, err := q.query(ctx, q.listAccountsStmt, listAccounts, arg.UserID, arg.IncludeArchived)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Type,
			&i.Balance,
			&i.Currency,
			&i.IsArchived,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAccountArchived = `-- name: SetAccountArchived :exec
UPDATE accounts
SET is_archived = $3
WHERE id = $1 AND user_id = $2
`

type SetAccountArchivedParams struct {
	ID         uuid.UUID `json:"id"`
	UserID     uuid.UUID `json:"userId"`
	IsArchived bool      `json:"isArchived"`
}

func (q *Queries) SetAccountArchived(ctx context.Context, arg SetAccountArchivedParams) error {
	_, err := q.exec(ctx, q.setAccountArchivedStmt, setAccountArchived, arg.ID, arg.UserID, arg.IsArchived)
	return err
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE accounts
SET name = $3,
    type = $4,
    currency = $5
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, type, balance, currency, is_archived, created_at, updated_at
`

type UpdateAccountParams struct {
	ID       uuid.UUID   `json:"id"`
	UserID   uuid.UUID   `json:"userId"`
	Name     string      `json:"name"`
	Type     AccountType `json:"type"`
	Currency string      `json:"currency"`
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error) {
	row := q.queryRow(ctx, q.updateAccountStmt, updateAccount,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Type,
		arg.Currency,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Balance,
		&i.Currency,
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
