// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.getAccountBalancesStmt, err = db.PrepareContext(ctx, getAccountBalances); err != nil {
		return nil, fmt.Errorf("error preparing query GetAccountBalances: %w", err)
	}
	if q.getMonthlyTrendStmt, err = db.PrepareContext(ctx, getMonthlyTrend); err != nil {
		return nil, fmt.Errorf("error preparing query GetMonthlyTrend: %w", err)
	}
	if q.getPeriodSummaryStmt, err = db.PrepareContext(ctx, getPeriodSummary); err != nil {
		return nil, fmt.Errorf("error preparing query GetPeriodSummary: %w", err)
	}
	if q.getRecentTransactionsStmt, err = db.PrepareContext(ctx, getRecentTransactions); err != nil {
		return nil, fmt.Errorf("error preparing query GetRecentTransactions: %w", err)
	}
	if q.getSpendingByCategoryStmt, err = db.PrepareContext(ctx, getSpendingByCategory); err != nil {
		return nil, fmt.Errorf("error preparing query GetSpendingByCategory: %w", err)
	}
	if q.getTotalBalanceStmt, err = db.PrepareContext(ctx, getTotalBalance); err != nil {
		return nil, fmt.Errorf("error preparing query GetTotalBalance: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.getAccountBalancesStmt != nil {
		if cerr := q.getAccountBalancesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAccountBalancesStmt: %w", cerr)
		}
	}
	if q.getMonthlyTrendStmt != nil {
		if cerr := q.getMonthlyTrendStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getMonthlyTrendStmt: %w", cerr)
		}
	}
	if q.getPeriodSummaryStmt != nil {
		if cerr := q.getPeriodSummaryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPeriodSummaryStmt: %w", cerr)
		}
	}
	if q.getRecentTransactionsStmt != nil {
		if cerr := q.getRecentTransactionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getRecentTransactionsStmt: %w", cerr)
		}
	}
	if q.getSpendingByCategoryStmt != nil {
		if cerr := q.getSpendingByCategoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSpendingByCategoryStmt: %w", cerr)
		}
	}
	if q.getTotalBalanceStmt != nil {
		if cerr := q.getTotalBalanceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTotalBalanceStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                        DBTX
	tx                        *sql.Tx
	getAccountBalancesStmt    *sql.Stmt
	getMonthlyTrendStmt       *sql.Stmt
	getPeriodSummaryStmt      *sql.Stmt
	getRecentTransactionsStmt *sql.Stmt
	getSpendingByCategoryStmt *sql.Stmt
	getTotalBalanceStmt       *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                        tx,
		tx:                        tx,
		getAccountBalancesStmt:    q.getAccountBalancesStmt,
		getMonthlyTrendStmt:       q.getMonthlyTrendStmt,
		getPeriodSummaryStmt:      q.getPeriodSummaryStmt,
		getRecentTransactionsStmt: q.getRecentTransactionsStmt,
		getSpendingByCategoryStmt: q.getSpendingByCategoryStmt,
		getTotalBalanceStmt:       q.getTotalBalanceStmt,
	}
}
