// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package repository

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const getAccountBalances = `-- name: GetAccountBalances :many
SELECT id, name, type, balance::text AS balance, currency
FROM accounts
WHERE user_id = $1 AND is_archived = FALSE
ORDER BY balance DESC
`

type GetAccountBalancesRow struct {
	ID       uuid.UUID   `json:"id"`
	Name     string      `json:"name"`
	Type     AccountType `json:"type"`
	Balance  string      `json:"balance"`
	Currency string      `json:"currency"`
}

func (q *Queries) GetAccountBalances(ctx context.Context, userID uuid.UUID) ([]GetAccountBalancesRow, error) {
	rows, err := q.query(ctx, q.getAccountBalancesStmt, getAccountBalances, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAccountBalancesRow
	for rows.Next() {
		var i GetAccountBalancesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Balance,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMonthlyTrend = `-- name: GetMonthlyTrend :many
SELECT
    to_char(m.month, 'YYYY-MM') AS period,
    COALESCE(SUM(CASE WHEN c.type = 'income'  THEN t.amount ELSE 0 END), 0)::text AS total_income,
    COALESCE(SUM(CASE WHEN c.type = 'expense' THEN t.amount ELSE 0 END), 0)::text AS total_expense
FROM generate_series($2::date, $3::date, INTERVAL '1 month') AS m(month)
LEFT JOIN transactions t
       ON t.user_id = $1
      AND t.transaction_date >= m.month
      AND t.transaction_date < (m.month + INTERVAL '1 month')
LEFT JOIN categories c ON c.id = t.category_id
GROUP BY m.month
ORDER BY m.month
`

type GetMonthlyTrendParams struct {
	UserID     uuid.UUID `json:"userId"`
	StartMonth time.Time `json:"startMonth"`
	EndMonth   time.Time `json:"endMonth"`
}

type GetMonthlyTrendRow struct {
	Period       string `json:"period"`
	TotalIncome  string `json:"totalIncome"`
	TotalExpense string `json:"totalExpense"`
}

// One row per month in the requested window, including months with no activity.
func (q *Queries) GetMonthlyTrend(ctx context.Context, arg GetMonthlyTrendParams) ([]GetMonthlyTrendRow, error) {
	rows, err := q.query(ctx, q.getMonthlyTrendStmt, getMonthlyTrend, arg.UserID, arg.StartMonth, arg.EndMonth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMonthlyTrendRow
	for rows.Next() {
		var i GetMonthlyTrendRow
		if err := rows.Scan(&i.Period, &i.TotalIncome, &i.TotalExpense); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPeriodSummary = `-- name: GetPeriodSummary :one
SELECT
    COALESCE(SUM(CASE WHEN c.type = 'income'  THEN t.amount ELSE 0 END), 0)::text AS total_income,
    COALESCE(SUM(CASE WHEN c.type = 'expense' THEN t.amount ELSE 0 END), 0)::text AS total_expense,
    COUNT(*) AS transaction_count
FROM transactions t
JOIN categories c ON c.id = t.category_id
WHERE t.user_id = $1
  AND t.transaction_date >= $2
  AND t.transaction_date <= $3
`

type GetPeriodSummaryParams struct {
	UserID    uuid.UUID `json:"userId"`
	StartDate time.Time `json:"startDate"`
	EndDate   time.Time `json:"endDate"`
}

type GetPeriodSummaryRow struct {
	TotalIncome      string `json:"totalIncome"`
	TotalExpense     string `json:"totalExpense"`
	TransactionCount int64  `json:"transactionCount"`
}

// Transfers are excluded: moving money between own accounts is not income or expense.
func (q *Queries) GetPeriodSummary(ctx context.Context, arg GetPeriodSummaryParams) (GetPeriodSummaryRow, error) {
	row := q.queryRow(ctx, q.getPeriodSummaryStmt, getPeriodSummary, arg.UserID, arg.StartDate, arg.EndDate)
	var i GetPeriodSummaryRow
	err := row.Scan(&i.TotalIncome, &i.TotalExpense, &i.TransactionCount)
	return i, err
}

const getRecentTransactions = `-- name: GetRecentTransactions :many
SELECT
    t.id,
    a.name AS account_name,
    c.name AS category_name,
    c.type AS category_type,
    c.icon AS category_icon,
    c.color AS category_color,
    t.amount::text AS amount,
    t.transaction_date,
    t.description
FROM transactions t
JOIN accounts a ON a.id = t.account_id
JOIN categories c ON c.id = t.category_id
WHERE t.user_id = $1
ORDER BY t.transaction_date DESC, t.created_at DESC
LIMIT $2
`

type GetRecentTransactionsParams struct {
	UserID   uuid.UUID `json:"userId"`
	RowLimit int32     `json:"rowLimit"`
}

type GetRecentTransactionsRow struct {
	ID              uuid.UUID      `json:"id"`
	AccountName     string         `json:"accountName"`
	CategoryName    string         `json:"categoryName"`
	CategoryType    CategoryType   `json:"categoryType"`
	CategoryIcon    sql.NullString `json:"categoryIcon"`
	CategoryColor   sql.NullString `json:"categoryColor"`
	Amount          string         `json:"amount"`
	TransactionDate time.Time      `json:"transactionDate"`
	Description     sql.NullString `json:"description"`
}

func (q *Queries) GetRecentTransactions(ctx context.Context, arg GetRecentTransactionsParams) ([]GetRecentTransactionsRow, error) {
	rows, err := q.query(ctx, q.getRecentTransactionsStmt, getRecentTransactions, arg.UserID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentTransactionsRow
	for rows.Next() {
		var i GetRecentTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountName,
			&i.CategoryName,
			&i.CategoryType,
			&i.CategoryIcon,
			&i.CategoryColor,
			&i.Amount,
			&i.TransactionDate,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSpendingByCategory = `-- name: GetSpendingByCategory :many
SELECT
    c.id AS category_id,
    c.name AS category_name,
    c.icon AS category_icon,
    c.color AS category_color,
    SUM(t.amount)::text AS total,
    COUNT(*) AS transaction_count
FROM transactions t
JOIN categories c ON c.id = t.category_id
WHERE t.user_id = $1
  AND c.type = $2::category_type
  AND t.transaction_date >= $3
  AND t.transaction_date <= $4
GROUP BY c.id, c.name, c.icon, c.color
ORDER BY SUM(t.amount) DESC
`

type GetSpendingByCategoryParams struct {
	UserID    uuid.UUID    `json:"userId"`
	Type      CategoryType `json:"type"`
	StartDate time.Time    `json:"startDate"`
	EndDate   time.Time    `json:"endDate"`
}

type GetSpendingByCategoryRow struct {
	CategoryID       uuid.UUID      `json:"categoryId"`
	CategoryName     string         `json:"categoryName"`
	CategoryIcon     sql.NullString `json:"categoryIcon"`
	CategoryColor    sql.NullString `json:"categoryColor"`
	Total            string         `json:"total"`
	TransactionCount int64          `json:"transactionCount"`
}

func (q *Queries) GetSpendingByCategory(ctx context.Context, arg GetSpendingByCategoryParams) ([]GetSpendingByCategoryRow, error) {
	rows, err := q.query(ctx, q.getSpendingByCategoryStmt, getSpendingByCategory,
		arg.UserID,
		arg.Type,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSpendingByCategoryRow
	for rows.Next() {
		var i GetSpendingByCategoryRow
		if err := rows.Scan(
			&i.CategoryID,
			&i.CategoryName,
			&i.CategoryIcon,
			&i.CategoryColor,
			&i.Total,
			&i.TransactionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalBalance = `-- name: GetTotalBalance :one
SELECT COALESCE(SUM(balance), 0)::text AS total_balance
FROM accounts
WHERE user_id = $1 AND is_archived = FALSE
`

func (q *Queries) GetTotalBalance(ctx context.Context, userID uuid.UUID) (string, error) {
	row := q.queryRow(ctx, q.getTotalBalanceStmt, getTotalBalance, userID)
	var total_balance string
	err := row.Scan(&total_balance)
	return total_balance, err
}
