// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Account struct {
	ID        uuid.UUID   `json:"id"`
	UserID    uuid.UUID   `json:"userId"`
	Name      string      `json:"name"`
	Type      interface{} `json:"type"`
	Balance   string      `json:"balance"`
	CreatedAt time.Time   `json:"createdAt"`
	UpdatedAt time.Time   `json:"updatedAt"`
}

type Category struct {
	ID        uuid.UUID      `json:"id"`
	UserID    uuid.NullUUID  `json:"userId"`
	Name      string         `json:"name"`
	Type      interface{}    `json:"type"`
	Icon      sql.NullString `json:"icon"`
	CreatedAt time.Time      `json:"createdAt"`
	UpdatedAt time.Time      `json:"updatedAt"`
}

type Transaction struct {
	ID              uuid.UUID      `json:"id"`
	UserID          uuid.UUID      `json:"userId"`
	AccountID       uuid.UUID      `json:"accountId"`
	CategoryID      uuid.UUID      `json:"categoryId"`
	ToAccountID     uuid.NullUUID  `json:"toAccountId"`
	Amount          string         `json:"amount"`
	TransactionDate time.Time      `json:"transactionDate"`
	Description     sql.NullString `json:"description"`
	CreatedAt       time.Time      `json:"createdAt"`
	UpdatedAt       time.Time      `json:"updatedAt"`
}

type User struct {
	ID                 uuid.UUID      `json:"id"`
	Username           string         `json:"username"`
	IsActive           bool           `json:"isActive"`
	Email              string         `json:"email"`
	PasswordHash       string         `json:"passwordHash"`
	CreatedAt          time.Time      `json:"createdAt"`
	UpdatedAt          time.Time      `json:"updatedAt"`
	ResetPasswordToken sql.NullString `json:"resetPasswordToken"`
}
