// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"database/sql"
	"time"
)

type Account struct {
	ID        int32          `json:"id"`
	UserID    int32          `json:"userId"`
	Name      string         `json:"name"`
	Type      interface{}    `json:"type"`
	Balance   sql.NullString `json:"balance"`
	CreatedAt sql.NullTime   `json:"createdAt"`
}

type Category struct {
	ID     int32          `json:"id"`
	UserID sql.NullInt32  `json:"userId"`
	Name   string         `json:"name"`
	Type   interface{}    `json:"type"`
	Icon   sql.NullString `json:"icon"`
}

type Transaction struct {
	ID              int32          `json:"id"`
	UserID          int32          `json:"userId"`
	AccountID       int32          `json:"accountId"`
	CategoryID      int32          `json:"categoryId"`
	ToAccountID     sql.NullInt32  `json:"toAccountId"`
	Amount          string         `json:"amount"`
	TransactionDate time.Time      `json:"transactionDate"`
	Description     sql.NullString `json:"description"`
	CreatedAt       sql.NullTime   `json:"createdAt"`
}

type User struct {
	ID           int32        `json:"id"`
	Username     string       `json:"username"`
	IsActive     sql.NullBool `json:"isActive"`
	Email        string       `json:"email"`
	PasswordHash string       `json:"passwordHash"`
	CreatedAt    sql.NullTime `json:"createdAt"`
	UpdatedAt    sql.NullTime `json:"updatedAt"`
}
