// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.deleteBudgetStmt, err = db.PrepareContext(ctx, deleteBudget); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteBudget: %w", err)
	}
	if q.getBudgetByIDStmt, err = db.PrepareContext(ctx, getBudgetByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetBudgetByID: %w", err)
	}
	if q.listBudgetsStmt, err = db.PrepareContext(ctx, listBudgets); err != nil {
		return nil, fmt.Errorf("error preparing query ListBudgets: %w", err)
	}
	if q.updateBudgetStmt, err = db.PrepareContext(ctx, updateBudget); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateBudget: %w", err)
	}
	if q.upsertBudgetStmt, err = db.PrepareContext(ctx, upsertBudget); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertBudget: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.deleteBudgetStmt != nil {
		if cerr := q.deleteBudgetStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteBudgetStmt: %w", cerr)
		}
	}
	if q.getBudgetByIDStmt != nil {
		if cerr := q.getBudgetByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getBudgetByIDStmt: %w", cerr)
		}
	}
	if q.listBudgetsStmt != nil {
		if cerr := q.listBudgetsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listBudgetsStmt: %w", cerr)
		}
	}
	if q.updateBudgetStmt != nil {
		if cerr := q.updateBudgetStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateBudgetStmt: %w", cerr)
		}
	}
	if q.upsertBudgetStmt != nil {
		if cerr := q.upsertBudgetStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertBudgetStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                DBTX
	tx                *sql.Tx
	deleteBudgetStmt  *sql.Stmt
	getBudgetByIDStmt *sql.Stmt
	listBudgetsStmt   *sql.Stmt
	updateBudgetStmt  *sql.Stmt
	upsertBudgetStmt  *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                tx,
		tx:                tx,
		deleteBudgetStmt:  q.deleteBudgetStmt,
		getBudgetByIDStmt: q.getBudgetByIDStmt,
		listBudgetsStmt:   q.listBudgetsStmt,
		updateBudgetStmt:  q.updateBudgetStmt,
		upsertBudgetStmt:  q.upsertBudgetStmt,
	}
}
