// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package repository

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const deleteBudget = `-- name: DeleteBudget :execrows
DELETE FROM budgets
WHERE id = $1 AND user_id = $2
`

type DeleteBudgetParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"userId"`
}

func (q *Queries) DeleteBudget(ctx context.Context, arg DeleteBudgetParams) (int64, error) {
	result, err := q.exec(ctx, q.deleteBudgetStmt, deleteBudget, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getBudgetByID = `-- name: GetBudgetByID :one
SELECT id, user_id, category_id, amount, period_month, created_at, updated_at
FROM budgets
WHERE id = $1 AND user_id = $2
LIMIT 1
`

type GetBudgetByIDParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"userId"`
}

func (q *Queries) GetBudgetByID(ctx context.Context, arg GetBudgetByIDParams) (Budget, error) {
	row := q.queryRow(ctx, q.getBudgetByIDStmt, getBudgetByID, arg.ID, arg.UserID)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Amount,
		&i.PeriodMonth,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBudgets = `-- name: ListBudgets :many
SELECT
    b.id,
    b.category_id,
    c.name AS category_name,
    c.icon AS category_icon,
    c.color AS category_color,
    b.amount::text AS amount,
    b.period_month,
    COALESCE((
        SELECT SUM(t.amount)
        FROM transactions t
        WHERE t.user_id = b.user_id
          AND t.category_id = b.category_id
          AND t.transaction_date >= b.period_month
          AND t.transaction_date < (b.period_month + INTERVAL '1 month')
    ), 0)::text AS spent,
    b.created_at,
    b.updated_at
FROM budgets b
JOIN categories c ON c.id = b.category_id
WHERE b.user_id = $1 AND b.period_month = $2
ORDER BY c.name
`

type ListBudgetsParams struct {
	UserID      uuid.UUID `json:"userId"`
	PeriodMonth time.Time `json:"periodMonth"`
}

type ListBudgetsRow struct {
	ID            uuid.UUID      `json:"id"`
	CategoryID    uuid.UUID      `json:"categoryId"`
	CategoryName  string         `json:"categoryName"`
	CategoryIcon  sql.NullString `json:"categoryIcon"`
	CategoryColor sql.NullString `json:"categoryColor"`
	Amount        string         `json:"amount"`
	PeriodMonth   time.Time      `json:"periodMonth"`
	Spent         string         `json:"spent"`
	CreatedAt     time.Time      `json:"createdAt"`
	UpdatedAt     time.Time      `json:"updatedAt"`
}

// Pairs each budget with the amount actually spent in that month.
func (q *Queries) ListBudgets(ctx context.Context, arg ListBudgetsParams) ([]ListBudgetsRow, error) {
	rows, err := q.query(ctx, q.listBudgetsStmt, listBudgets, arg.UserID, arg.PeriodMonth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBudgetsRow
	for rows.Next() {
		var i ListBudgetsRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.CategoryName,
			&i.CategoryIcon,
			&i.CategoryColor,
			&i.Amount,
			&i.PeriodMonth,
			&i.Spent,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBudget = `-- name: UpdateBudget :one
UPDATE budgets
SET amount = $3
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, category_id, amount, period_month, created_at, updated_at
`

type UpdateBudgetParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"userId"`
	Amount string    `json:"amount"`
}

func (q *Queries) UpdateBudget(ctx context.Context, arg UpdateBudgetParams) (Budget, error) {
	row := q.queryRow(ctx, q.updateBudgetStmt, updateBudget, arg.ID, arg.UserID, arg.Amount)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Amount,
		&i.PeriodMonth,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertBudget = `-- name: UpsertBudget :one
INSERT INTO budgets (user_id, category_id, amount, period_month)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, category_id, period_month)
DO UPDATE SET amount = EXCLUDED.amount, updated_at = NOW()
RETURNING id, user_id, category_id, amount, period_month, created_at, updated_at
`

type UpsertBudgetParams struct {
	UserID      uuid.UUID `json:"userId"`
	CategoryID  uuid.UUID `json:"categoryId"`
	Amount      string    `json:"amount"`
	PeriodMonth time.Time `json:"periodMonth"`
}

func (q *Queries) UpsertBudget(ctx context.Context, arg UpsertBudgetParams) (Budget, error) {
	row := q.queryRow(ctx, q.upsertBudgetStmt, upsertBudget,
		arg.UserID,
		arg.CategoryID,
		arg.Amount,
		arg.PeriodMonth,
	)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Amount,
		&i.PeriodMonth,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
