// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package repository

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const countCategoryTransactions = `-- name: CountCategoryTransactions :one
SELECT COUNT(*)
FROM transactions
WHERE category_id = $1
`

func (q *Queries) CountCategoryTransactions(ctx context.Context, categoryID uuid.UUID) (int64, error) {
	row := q.queryRow(ctx, q.countCategoryTransactionsStmt, countCategoryTransactions, categoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (user_id, name, type, icon, color)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, name, type, icon, color, created_at, updated_at
`

type CreateCategoryParams struct {
	UserID uuid.NullUUID  `json:"userId"`
	Name   string         `json:"name"`
	Type   CategoryType   `json:"type"`
	Icon   sql.NullString `json:"icon"`
	Color  sql.NullString `json:"color"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.queryRow(ctx, q.createCategoryStmt, createCategory,
		arg.UserID,
		arg.Name,
		arg.Type,
		arg.Icon,
		arg.Color,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Icon,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :execrows
DELETE FROM categories
WHERE id = $1 AND user_id = $2
`

type DeleteCategoryParams struct {
	ID     uuid.UUID     `json:"id"`
	UserID uuid.NullUUID `json:"userId"`
}

func (q *Queries) DeleteCategory(ctx context.Context, arg DeleteCategoryParams) (int64, error) {
	result, err := q.exec(ctx, q.deleteCategoryStmt, deleteCategory, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, user_id, name, type, icon, color, created_at, updated_at,
       (user_id IS NULL)::boolean AS is_global
FROM categories
WHERE id = $1 AND (user_id = $2 OR user_id IS NULL)
LIMIT 1
`

type GetCategoryByIDParams struct {
	ID     uuid.UUID     `json:"id"`
	UserID uuid.NullUUID `json:"userId"`
}

type GetCategoryByIDRow struct {
	ID        uuid.UUID      `json:"id"`
	UserID    uuid.NullUUID  `json:"userId"`
	Name      string         `json:"name"`
	Type      CategoryType   `json:"type"`
	Icon      sql.NullString `json:"icon"`
	Color     sql.NullString `json:"color"`
	CreatedAt time.Time      `json:"createdAt"`
	UpdatedAt time.Time      `json:"updatedAt"`
	IsGlobal  bool           `json:"isGlobal"`
}

func (q *Queries) GetCategoryByID(ctx context.Context, arg GetCategoryByIDParams) (GetCategoryByIDRow, error) {
	row := q.queryRow(ctx, q.getCategoryByIDStmt, getCategoryByID, arg.ID, arg.UserID)
	var i GetCategoryByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Icon,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsGlobal,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, user_id, name, type, icon, color, created_at, updated_at,
       (user_id IS NULL)::boolean AS is_global
FROM categories
WHERE (user_id = $1 OR user_id IS NULL)
  AND ($2::category_type IS NULL OR type = $2::category_type)
ORDER BY type, name
`

type ListCategoriesParams struct {
	UserID uuid.NullUUID    `json:"userId"`
	Type   NullCategoryType `json:"type"`
}

type ListCategoriesRow struct {
	ID        uuid.UUID      `json:"id"`
	UserID    uuid.NullUUID  `json:"userId"`
	Name      string         `json:"name"`
	Type      CategoryType   `json:"type"`
	Icon      sql.NullString `json:"icon"`
	Color     sql.NullString `json:"color"`
	CreatedAt time.Time      `json:"createdAt"`
	UpdatedAt time.Time      `json:"updatedAt"`
	IsGlobal  bool           `json:"isGlobal"`
}

// Returns the user's own categories plus the global ones (user_id IS NULL).
func (q *Queries) ListCategories(ctx context.Context, arg ListCategoriesParams) ([]ListCategoriesRow, error) {
	rows, err := q.query(ctx, q.listCategoriesStmt, listCategories, arg.UserID, arg.Type)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCategoriesRow
	for rows.Next() {
		var i ListCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Type,
			&i.Icon,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsGlobal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET name = $3,
    type = $4,
    icon = $5,
    color = $6
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, type, icon, color, created_at, updated_at
`

type UpdateCategoryParams struct {
	ID     uuid.UUID      `json:"id"`
	UserID uuid.NullUUID  `json:"userId"`
	Name   string         `json:"name"`
	Type   CategoryType   `json:"type"`
	Icon   sql.NullString `json:"icon"`
	Color  sql.NullString `json:"color"`
}

// Scoped to user_id so global categories can never be edited.
func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.queryRow(ctx, q.updateCategoryStmt, updateCategory,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Type,
		arg.Icon,
		arg.Color,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Icon,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
