// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.adjustAccountBalanceStmt, err = db.PrepareContext(ctx, adjustAccountBalance); err != nil {
		return nil, fmt.Errorf("error preparing query AdjustAccountBalance: %w", err)
	}
	if q.countTransactionsStmt, err = db.PrepareContext(ctx, countTransactions); err != nil {
		return nil, fmt.Errorf("error preparing query CountTransactions: %w", err)
	}
	if q.createTransactionStmt, err = db.PrepareContext(ctx, createTransaction); err != nil {
		return nil, fmt.Errorf("error preparing query CreateTransaction: %w", err)
	}
	if q.deleteTransactionStmt, err = db.PrepareContext(ctx, deleteTransaction); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteTransaction: %w", err)
	}
	if q.getAccountForTransactionStmt, err = db.PrepareContext(ctx, getAccountForTransaction); err != nil {
		return nil, fmt.Errorf("error preparing query GetAccountForTransaction: %w", err)
	}
	if q.getCategoryForTransactionStmt, err = db.PrepareContext(ctx, getCategoryForTransaction); err != nil {
		return nil, fmt.Errorf("error preparing query GetCategoryForTransaction: %w", err)
	}
	if q.getTransactionByIDStmt, err = db.PrepareContext(ctx, getTransactionByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetTransactionByID: %w", err)
	}
	if q.getTransactionRawStmt, err = db.PrepareContext(ctx, getTransactionRaw); err != nil {
		return nil, fmt.Errorf("error preparing query GetTransactionRaw: %w", err)
	}
	if q.listTransactionsStmt, err = db.PrepareContext(ctx, listTransactions); err != nil {
		return nil, fmt.Errorf("error preparing query ListTransactions: %w", err)
	}
	if q.updateTransactionStmt, err = db.PrepareContext(ctx, updateTransaction); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateTransaction: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.adjustAccountBalanceStmt != nil {
		if cerr := q.adjustAccountBalanceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adjustAccountBalanceStmt: %w", cerr)
		}
	}
	if q.countTransactionsStmt != nil {
		if cerr := q.countTransactionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countTransactionsStmt: %w", cerr)
		}
	}
	if q.createTransactionStmt != nil {
		if cerr := q.createTransactionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createTransactionStmt: %w", cerr)
		}
	}
	if q.deleteTransactionStmt != nil {
		if cerr := q.deleteTransactionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteTransactionStmt: %w", cerr)
		}
	}
	if q.getAccountForTransactionStmt != nil {
		if cerr := q.getAccountForTransactionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAccountForTransactionStmt: %w", cerr)
		}
	}
	if q.getCategoryForTransactionStmt != nil {
		if cerr := q.getCategoryForTransactionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCategoryForTransactionStmt: %w", cerr)
		}
	}
	if q.getTransactionByIDStmt != nil {
		if cerr := q.getTransactionByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTransactionByIDStmt: %w", cerr)
		}
	}
	if q.getTransactionRawStmt != nil {
		if cerr := q.getTransactionRawStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTransactionRawStmt: %w", cerr)
		}
	}
	if q.listTransactionsStmt != nil {
		if cerr := q.listTransactionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listTransactionsStmt: %w", cerr)
		}
	}
	if q.updateTransactionStmt != nil {
		if cerr := q.updateTransactionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateTransactionStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                            DBTX
	tx                            *sql.Tx
	adjustAccountBalanceStmt      *sql.Stmt
	countTransactionsStmt         *sql.Stmt
	createTransactionStmt         *sql.Stmt
	deleteTransactionStmt         *sql.Stmt
	getAccountForTransactionStmt  *sql.Stmt
	getCategoryForTransactionStmt *sql.Stmt
	getTransactionByIDStmt        *sql.Stmt
	getTransactionRawStmt         *sql.Stmt
	listTransactionsStmt          *sql.Stmt
	updateTransactionStmt         *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                            tx,
		tx:                            tx,
		adjustAccountBalanceStmt:      q.adjustAccountBalanceStmt,
		countTransactionsStmt:         q.countTransactionsStmt,
		createTransactionStmt:         q.createTransactionStmt,
		deleteTransactionStmt:         q.deleteTransactionStmt,
		getAccountForTransactionStmt:  q.getAccountForTransactionStmt,
		getCategoryForTransactionStmt: q.getCategoryForTransactionStmt,
		getTransactionByIDStmt:        q.getTransactionByIDStmt,
		getTransactionRawStmt:         q.getTransactionRawStmt,
		listTransactionsStmt:          q.listTransactionsStmt,
		updateTransactionStmt:         q.updateTransactionStmt,
	}
}
