// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package repository

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const adjustAccountBalance = `-- name: AdjustAccountBalance :exec
UPDATE accounts
SET balance = balance + $3::numeric
WHERE id = $1 AND user_id = $2
`

type AdjustAccountBalanceParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"userId"`
	Delta  string    `json:"delta"`
}

// delta is applied as-is, so callers pass a negative value to debit.
func (q *Queries) AdjustAccountBalance(ctx context.Context, arg AdjustAccountBalanceParams) error {
	_, err := q.exec(ctx, q.adjustAccountBalanceStmt, adjustAccountBalance, arg.ID, arg.UserID, arg.Delta)
	return err
}

const countTransactions = `-- name: CountTransactions :one
SELECT COUNT(*)
FROM transactions t
JOIN categories c ON c.id = t.category_id
WHERE t.user_id = $1
  AND ($2::date IS NULL OR t.transaction_date >= $2::date)
  AND ($3::date IS NULL OR t.transaction_date <= $3::date)
  AND ($4::uuid IS NULL OR t.account_id = $4::uuid OR t.to_account_id = $4::uuid)
  AND ($5::uuid IS NULL OR t.category_id = $5::uuid)
  AND ($6::category_type IS NULL OR c.type = $6::category_type)
  AND ($7::text IS NULL OR t.description ILIKE '%' || $7::text || '%')
`

type CountTransactionsParams struct {
	UserID     uuid.UUID        `json:"userId"`
	StartDate  sql.NullTime     `json:"startDate"`
	EndDate    sql.NullTime     `json:"endDate"`
	AccountID  uuid.NullUUID    `json:"accountId"`
	CategoryID uuid.NullUUID    `json:"categoryId"`
	Type       NullCategoryType `json:"type"`
	Search     sql.NullString   `json:"search"`
}

func (q *Queries) CountTransactions(ctx context.Context, arg CountTransactionsParams) (int64, error) {
	row := q.queryRow(ctx, q.countTransactionsStmt, countTransactions,
		arg.UserID,
		arg.StartDate,
		arg.EndDate,
		arg.AccountID,
		arg.CategoryID,
		arg.Type,
		arg.Search,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (user_id, account_id, category_id, to_account_id, amount, transaction_date, description)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, account_id, category_id, to_account_id, amount, transaction_date, description, created_at, updated_at
`

type CreateTransactionParams struct {
	UserID          uuid.UUID      `json:"userId"`
	AccountID       uuid.UUID      `json:"accountId"`
	CategoryID      uuid.UUID      `json:"categoryId"`
	ToAccountID     uuid.NullUUID  `json:"toAccountId"`
	Amount          string         `json:"amount"`
	TransactionDate time.Time      `json:"transactionDate"`
	Description     sql.NullString `json:"description"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.queryRow(ctx, q.createTransactionStmt, createTransaction,
		arg.UserID,
		arg.AccountID,
		arg.CategoryID,
		arg.ToAccountID,
		arg.Amount,
		arg.TransactionDate,
		arg.Description,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.CategoryID,
		&i.ToAccountID,
		&i.Amount,
		&i.TransactionDate,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTransaction = `-- name: DeleteTransaction :execrows
DELETE FROM transactions
WHERE id = $1 AND user_id = $2
`

type DeleteTransactionParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"userId"`
}

func (q *Queries) DeleteTransaction(ctx context.Context, arg DeleteTransactionParams) (int64, error) {
	result, err := q.exec(ctx, q.deleteTransactionStmt, deleteTransaction, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAccountForTransaction = `-- name: GetAccountForTransaction :one
SELECT id, name, is_archived
FROM accounts
WHERE id = $1 AND user_id = $2
LIMIT 1
`

type GetAccountForTransactionParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"userId"`
}

type GetAccountForTransactionRow struct {
	ID         uuid.UUID `json:"id"`
	Name       string    `json:"name"`
	IsArchived bool      `json:"isArchived"`
}

func (q *Queries) GetAccountForTransaction(ctx context.Context, arg GetAccountForTransactionParams) (GetAccountForTransactionRow, error) {
	row := q.queryRow(ctx, q.getAccountForTransactionStmt, getAccountForTransaction, arg.ID, arg.UserID)
	var i GetAccountForTransactionRow
	err := row.Scan(&i.ID, &i.Name, &i.IsArchived)
	return i, err
}

const getCategoryForTransaction = `-- name: GetCategoryForTransaction :one
SELECT id, name, type
FROM categories
WHERE id = $1 AND (user_id = $2 OR user_id IS NULL)
LIMIT 1
`

type GetCategoryForTransactionParams struct {
	ID     uuid.UUID     `json:"id"`
	UserID uuid.NullUUID `json:"userId"`
}

type GetCategoryForTransactionRow struct {
	ID   uuid.UUID    `json:"id"`
	Name string       `json:"name"`
	Type CategoryType `json:"type"`
}

func (q *Queries) GetCategoryForTransaction(ctx context.Context, arg GetCategoryForTransactionParams) (GetCategoryForTransactionRow, error) {
	row := q.queryRow(ctx, q.getCategoryForTransactionStmt, getCategoryForTransaction, arg.ID, arg.UserID)
	var i GetCategoryForTransactionRow
	err := row.Scan(&i.ID, &i.Name, &i.Type)
	return i, err
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT
    t.id,
    t.account_id,
    a.name AS account_name,
    t.to_account_id,
    ta.name AS to_account_name,
    t.category_id,
    c.name AS category_name,
    c.type AS category_type,
    c.icon AS category_icon,
    c.color AS category_color,
    t.amount::text AS amount,
    t.transaction_date,
    t.description,
    t.created_at,
    t.updated_at
FROM transactions t
JOIN accounts a ON a.id = t.account_id
JOIN categories c ON c.id = t.category_id
LEFT JOIN accounts ta ON ta.id = t.to_account_id
WHERE t.id = $1 AND t.user_id = $2
LIMIT 1
`

type GetTransactionByIDParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"userId"`
}

type GetTransactionByIDRow struct {
	ID              uuid.UUID      `json:"id"`
	AccountID       uuid.UUID      `json:"accountId"`
	AccountName     string         `json:"accountName"`
	ToAccountID     uuid.NullUUID  `json:"toAccountId"`
	ToAccountName   sql.NullString `json:"toAccountName"`
	CategoryID      uuid.UUID      `json:"categoryId"`
	CategoryName    string         `json:"categoryName"`
	CategoryType    CategoryType   `json:"categoryType"`
	CategoryIcon    sql.NullString `json:"categoryIcon"`
	CategoryColor   sql.NullString `json:"categoryColor"`
	Amount          string         `json:"amount"`
	TransactionDate time.Time      `json:"transactionDate"`
	Description     sql.NullString `json:"description"`
	CreatedAt       time.Time      `json:"createdAt"`
	UpdatedAt       time.Time      `json:"updatedAt"`
}

func (q *Queries) GetTransactionByID(ctx context.Context, arg GetTransactionByIDParams) (GetTransactionByIDRow, error) {
	row := q.queryRow(ctx, q.getTransactionByIDStmt, getTransactionByID, arg.ID, arg.UserID)
	var i GetTransactionByIDRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.AccountName,
		&i.ToAccountID,
		&i.ToAccountName,
		&i.CategoryID,
		&i.CategoryName,
		&i.CategoryType,
		&i.CategoryIcon,
		&i.CategoryColor,
		&i.Amount,
		&i.TransactionDate,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTransactionRaw = `-- name: GetTransactionRaw :one
SELECT id, user_id, account_id, category_id, to_account_id, amount::text AS amount, transaction_date, description
FROM transactions
WHERE id = $1 AND user_id = $2
LIMIT 1
`

type GetTransactionRawParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"userId"`
}

type GetTransactionRawRow struct {
	ID              uuid.UUID      `json:"id"`
	UserID          uuid.UUID      `json:"userId"`
	AccountID       uuid.UUID      `json:"accountId"`
	CategoryID      uuid.UUID      `json:"categoryId"`
	ToAccountID     uuid.NullUUID  `json:"toAccountId"`
	Amount          string         `json:"amount"`
	TransactionDate time.Time      `json:"transactionDate"`
	Description     sql.NullString `json:"description"`
}

func (q *Queries) GetTransactionRaw(ctx context.Context, arg GetTransactionRawParams) (GetTransactionRawRow, error) {
	row := q.queryRow(ctx, q.getTransactionRawStmt, getTransactionRaw, arg.ID, arg.UserID)
	var i GetTransactionRawRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.CategoryID,
		&i.ToAccountID,
		&i.Amount,
		&i.TransactionDate,
		&i.Description,
	)
	return i, err
}

const listTransactions = `-- name: ListTransactions :many
SELECT
    t.id,
    t.account_id,
    a.name AS account_name,
    t.to_account_id,
    ta.name AS to_account_name,
    t.category_id,
    c.name AS category_name,
    c.type AS category_type,
    c.icon AS category_icon,
    c.color AS category_color,
    t.amount::text AS amount,
    t.transaction_date,
    t.description,
    t.created_at,
    t.updated_at
FROM transactions t
JOIN accounts a ON a.id = t.account_id
JOIN categories c ON c.id = t.category_id
LEFT JOIN accounts ta ON ta.id = t.to_account_id
WHERE t.user_id = $1
  AND ($2::date IS NULL OR t.transaction_date >= $2::date)
  AND ($3::date IS NULL OR t.transaction_date <= $3::date)
  AND ($4::uuid IS NULL OR t.account_id = $4::uuid OR t.to_account_id = $4::uuid)
  AND ($5::uuid IS NULL OR t.category_id = $5::uuid)
  AND ($6::category_type IS NULL OR c.type = $6::category_type)
  AND ($7::text IS NULL OR t.description ILIKE '%' || $7::text || '%')
ORDER BY t.transaction_date DESC, t.created_at DESC
LIMIT $9 OFFSET $8
`

type ListTransactionsParams struct {
	UserID     uuid.UUID        `json:"userId"`
	StartDate  sql.NullTime     `json:"startDate"`
	EndDate    sql.NullTime     `json:"endDate"`
	AccountID  uuid.NullUUID    `json:"accountId"`
	CategoryID uuid.NullUUID    `json:"categoryId"`
	Type       NullCategoryType `json:"type"`
	Search     sql.NullString   `json:"search"`
	RowOffset  int32            `json:"rowOffset"`
	RowLimit   int32            `json:"rowLimit"`
}

type ListTransactionsRow struct {
	ID              uuid.UUID      `json:"id"`
	AccountID       uuid.UUID      `json:"accountId"`
	AccountName     string         `json:"accountName"`
	ToAccountID     uuid.NullUUID  `json:"toAccountId"`
	ToAccountName   sql.NullString `json:"toAccountName"`
	CategoryID      uuid.UUID      `json:"categoryId"`
	CategoryName    string         `json:"categoryName"`
	CategoryType    CategoryType   `json:"categoryType"`
	CategoryIcon    sql.NullString `json:"categoryIcon"`
	CategoryColor   sql.NullString `json:"categoryColor"`
	Amount          string         `json:"amount"`
	TransactionDate time.Time      `json:"transactionDate"`
	Description     sql.NullString `json:"description"`
	CreatedAt       time.Time      `json:"createdAt"`
	UpdatedAt       time.Time      `json:"updatedAt"`
}

func (q *Queries) ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]ListTransactionsRow, error) {
	rows, err := q.query(ctx, q.listTransactionsStmt, listTransactions,
		arg.UserID,
		arg.StartDate,
		arg.EndDate,
		arg.AccountID,
		arg.CategoryID,
		arg.Type,
		arg.Search,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransactionsRow
	for rows.Next() {
		var i ListTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.AccountName,
			&i.ToAccountID,
			&i.ToAccountName,
			&i.CategoryID,
			&i.CategoryName,
			&i.CategoryType,
			&i.CategoryIcon,
			&i.CategoryColor,
			&i.Amount,
			&i.TransactionDate,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transactions
SET account_id = $3,
    category_id = $4,
    to_account_id = $5,
    amount = $6,
    transaction_date = $7,
    description = $8
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, account_id, category_id, to_account_id, amount, transaction_date, description, created_at, updated_at
`

type UpdateTransactionParams struct {
	ID              uuid.UUID      `json:"id"`
	UserID          uuid.UUID      `json:"userId"`
	AccountID       uuid.UUID      `json:"accountId"`
	CategoryID      uuid.UUID      `json:"categoryId"`
	ToAccountID     uuid.NullUUID  `json:"toAccountId"`
	Amount          string         `json:"amount"`
	TransactionDate time.Time      `json:"transactionDate"`
	Description     sql.NullString `json:"description"`
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error) {
	row := q.queryRow(ctx, q.updateTransactionStmt, updateTransaction,
		arg.ID,
		arg.UserID,
		arg.AccountID,
		arg.CategoryID,
		arg.ToAccountID,
		arg.Amount,
		arg.TransactionDate,
		arg.Description,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.CategoryID,
		&i.ToAccountID,
		&i.Amount,
		&i.TransactionDate,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
