// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package repository

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, username, password_hash, created_at)
VALUES ($1, $2, $3, now())
RETURNING id
`

type CreateUserParams struct {
	Email        string `json:"email"`
	Username     string `json:"username"`
	PasswordHash string `json:"passwordHash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (uuid.UUID, error) {
	row := q.queryRow(ctx, q.createUserStmt, createUser, arg.Email, arg.Username, arg.PasswordHash)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password_hash
FROM users
WHERE email = $1
LIMIT 1
`

type GetUserByEmailRow struct {
	ID           uuid.UUID `json:"id"`
	Username     string    `json:"username"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"passwordHash"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.queryRow(ctx, q.getUserByEmailStmt, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
	)
	return i, err
}

const getUserByResetToken = `-- name: GetUserByResetToken :one
SELECT id, username, email
FROM users
WHERE reset_password_token = $1
LIMIT 1
`

type GetUserByResetTokenRow struct {
	ID       uuid.UUID `json:"id"`
	Username string    `json:"username"`
	Email    string    `json:"email"`
}

func (q *Queries) GetUserByResetToken(ctx context.Context, resetPasswordToken sql.NullString) (GetUserByResetTokenRow, error) {
	row := q.queryRow(ctx, q.getUserByResetTokenStmt, getUserByResetToken, resetPasswordToken)
	var i GetUserByResetTokenRow
	err := row.Scan(&i.ID, &i.Username, &i.Email)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = $2,
    reset_password_token = null,
    updated_at = now()
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash string    `json:"passwordHash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.exec(ctx, q.updateUserPasswordStmt, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUserResetToken = `-- name: UpdateUserResetToken :exec
UPDATE users
SET reset_password_token = $2,
    updated_at = now()
WHERE id = $1
`

type UpdateUserResetTokenParams struct {
	ID                 uuid.UUID      `json:"id"`
	ResetPasswordToken sql.NullString `json:"resetPasswordToken"`
}

func (q *Queries) UpdateUserResetToken(ctx context.Context, arg UpdateUserResetTokenParams) error {
	_, err := q.exec(ctx, q.updateUserResetTokenStmt, updateUserResetToken, arg.ID, arg.ResetPasswordToken)
	return err
}
